### ISSUE TITLE
Local variable 'driver' referenced before assignment

### ISSUE THREAD

**Issue by Alden-G878** [SeanDaBlack/WreckItRalphs#2]
Before I get into the error, I would like to point out that this was happening before the job listing went down, and the error type leads me to believe that the existance of the job listing is unrelated. The error here is `local variable 'driver' referenced before assignment`, while the error when running the script on the taken down site is `FAILED TO START DRIVER: 'NoneType' object has no attribute 'click'`.

When trying to run the script on Google Colab, I get an error that prevents the script from running. 

I can properly clone the script into the Google Colab, as seen here: 
```
/root
Cloning into 'WreckItRalphs'...
warning: --local is ignored
remote: Enumerating objects: 208, done.
remote: Counting objects: 100% (208/208), done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 208 (delta 97), reused 201 (delta 90), pack-reused 0
Receiving objects: 100% (208/208), 312.34 KiB | 8.22 MiB/s, done.
Resolving deltas: 100% (97/97), done.
/root/WreckItRalphs
constants  main.py    requirements.txt	resumeSrc
LICENSE    README.md  resume_faker.py
Requirement already satisfied: certifi==2021.5.30 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 1)) (2021.5.30)
Requirement already satisfied: charset-normalizer==2.0.4 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 2)) (2.0.4)
Requirement already satisfied: idna==3.2 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 3)) (3.2)
Requirement already satisfied: requests==2.26.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 4)) (2.26.0)
Requirement already satisfied: selenium==3.141.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 5)) (3.141.0)
Requirement already satisfied: urllib3==1.26.6 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 6)) (1.26.6)
Requirement already satisfied: Faker==9.9.1 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 7)) (9.9.1)
Requirement already satisfied: webdriver-manager==3.5.2 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 8)) (3.5.2)
Requirement already satisfied: pydub==0.25.1 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 9)) (0.25.1)
Requirement already satisfied: fpdf==1.7.2 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 10)) (1.7.2)
Requirement already satisfied: text-unidecode==1.3 in /usr/local/lib/python3.7/dist-packages (from Faker==9.9.1->-r requirements.txt (line 7)) (1.3)
Requirement already satisfied: typing-extensions>=3.10.0.2 in /usr/local/lib/python3.7/dist-packages (from Faker==9.9.1->-r requirements.txt (line 7)) (3.10.0.2)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.7/dist-packages (from Faker==9.9.1->-r requirements.txt (line 7)) (2.8.2)
Requirement already satisfied: configparser in /usr/local/lib/python3.7/dist-packages (from webdriver-manager==3.5.2->-r requirements.txt (line 8)) (5.2.0)
Requirement already satisfied: crayons in /usr/local/lib/python3.7/dist-packages (from webdriver-manager==3.5.2->-r requirements.txt (line 8)) (0.4.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.4->Faker==9.9.1->-r requirements.txt (line 7)) (1.15.0)
Requirement already satisfied: colorama in /usr/local/lib/python3.7/dist-packages (from crayons->webdriver-manager==3.5.2->-r requirements.txt (line 8)) (0.4.4)
Ign:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:4 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Hit:5 http://archive.ubuntu.com/ubuntu bionic InRelease
Ign:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release
Hit:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:10 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Hit:11 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Get:12 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:13 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [913 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3,123 kB]
Fetched 4,288 kB in 4s (1,110 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
chromium-chromedriver is already the newest version (99.0.4844.84-0ubuntu0.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 81 not upgraded.
```

But when I then run the python script (with the --cloud flag) I get this error: 
```USING GUERRILLA TO CREATE EMAIL
EMAIL CREATED
FAILED TO CREATE ACCOUNT: local variable 'driver' referenced before assignment
FAILED TO FILL OUT APPLICATION AND SUBMIT: local variable 'driver' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 395, in main
    fill_out_application_and_submit(driver, random_city, fake_identity, appCount)
UnboundLocalError: local variable 'driver' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 407, in <module>
    main()
  File "main.py", line 399, in main
    driver.close()
UnboundLocalError: local variable 'driver' referenced before assignment
```
I was unable to replicate the error on my local machine, mostly since the job application is down so the program quits before reaching this point.

**Comment by tracitalynne** [comment]
I got this too! :)  I love this effort! Thanks!

**Comment by hepaestus** [comment]
Me too

**Comment by c01dc0ffee** [comment]
Looks like #1
